<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ibtesam Ifaz">
<meta name="dcterms.date" content="2026-04-24">

<title>Cafés Vs. Pubs in Melbourne – Ibtesam Ifaz</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-969ddfa49e00a70eb3423444dbc81f6c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7c8793e99a21e081e2bb8d69993efb75.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-6c9d4b6e8397689ef559897df4fbe577.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-7c8793e99a21e081e2bb8d69993efb75.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Ibtesam Ifaz</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="./cafes_vs_pubs.html">
 <span class="dropdown-text">Cafés vs Pubs in Melbourne</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./election_analytics.html">
 <span class="dropdown-text">National Election Analytics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./military_spending_report.html">
 <span class="dropdown-text">Military Spending Report</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/YOUR_USERNAME"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/YOUR_USERNAME"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data-wrangling-and-checking" id="toc-data-wrangling-and-checking" class="nav-link" data-scroll-target="#data-wrangling-and-checking"><span class="header-section-number">2</span> Data Wrangling and Checking</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">2.1</span> Data Sources</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">2.2</span> Data Wrangling</a></li>
  <li><a href="#data-checking" id="toc-data-checking" class="nav-link" data-scroll-target="#data-checking"><span class="header-section-number">2.3</span> Data Checking</a></li>
  </ul></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration"><span class="header-section-number">3</span> Data Exploration</a>
  <ul class="collapse">
  <li><a href="#q1-how-does-the-distribution-of-cafés-and-pubs-vary-across-melbourne-areas" id="toc-q1-how-does-the-distribution-of-cafés-and-pubs-vary-across-melbourne-areas" class="nav-link" data-scroll-target="#q1-how-does-the-distribution-of-cafés-and-pubs-vary-across-melbourne-areas"><span class="header-section-number">3.1</span> Q1: How does the distribution of cafés and pubs vary across Melbourne areas?</a></li>
  <li><a href="#q2-how-do-pub-to-café-ratios-differ-across-melbourne-areas-and-how-have-these-changed-over-time" id="toc-q2-how-do-pub-to-café-ratios-differ-across-melbourne-areas-and-how-have-these-changed-over-time" class="nav-link" data-scroll-target="#q2-how-do-pub-to-café-ratios-differ-across-melbourne-areas-and-how-have-these-changed-over-time"><span class="header-section-number">3.2</span> Q2: How do pub-to-café ratios differ across Melbourne areas, and how have these changed over time?</a></li>
  <li><a href="#q3-how-do-income-levels-and-age-distributions-relate-to-the-pub-to-café-ratio" id="toc-q3-how-do-income-levels-and-age-distributions-relate-to-the-pub-to-café-ratio" class="nav-link" data-scroll-target="#q3-how-do-income-levels-and-age-distributions-relate-to-the-pub-to-café-ratio"><span class="header-section-number">3.3</span> Q3: How do income levels and age distributions relate to the pub-to-café ratio?</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">4</span> Conclusion</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection"><span class="header-section-number">5</span> Reflection</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography"><span class="header-section-number">6</span> Bibliography</a></li>
  <li><a href="#generative-ai-declaration" id="toc-generative-ai-declaration" class="nav-link" data-scroll-target="#generative-ai-declaration"><span class="header-section-number">7</span> Generative AI Declaration</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Cafés Vs. Pubs in Melbourne</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ibtesam Ifaz </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p><strong>Project Title:</strong> Cafés Vs. Pubs in Melbourne</p>
<p>Melbourne is internationally recognised as one of the world’s great coffee cities, yet it also maintains a deeply ingrained pub culture. Recent research indicates that younger Australians are drinking less alcohol than previous generations <span class="citation" data-cites="aihw2024">[@aihw2024]</span>, which raises an interesting question about how this cultural shift may be reflected in the physical landscape of Melbourne’s hospitality sector. This project explores the distribution of cafés and pubs across the City of Melbourne’s defined local areas, examining how these venues are distributed, how their relative proportions have changed over time, and whether the balance between café and pub culture relates to the socioeconomic and demographic character of different neighbourhoods.</p>
<p>The findings are relevant to a broad range of audiences: potential hospitality business owners and investors seeking to identify underserved markets, urban planners and local government officials interested in how venues shape neighbourhood character, and researchers studying the relationship between place-based consumption patterns and demographics.</p>
<p><strong>Questions addressed in this report:</strong></p>
<ol type="1">
<li>How does the distribution of cafés and pubs vary across different areas of Melbourne?</li>
<li>How do pub-to-café ratios differ across Melbourne areas, and how have these ratios changed over time?</li>
<li>How do income levels and age distributions relate to the pub-to-café ratio across different areas?</li>
</ol>
</section>
<section id="data-wrangling-and-checking" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data Wrangling and Checking</h1>
<section id="data-sources" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">2.1</span> Data Sources</h2>
<p>Three data sources were used in this analysis:</p>
<p><strong>Source A – City of Melbourne: Cafés and Restaurants with Seating Capacity (2002–2024).</strong> This tabular dataset contains 66,356 observations across 15 columns. Each row represents a specific seating-type record for a food/beverage venue in a given census year. Key attributes include <code>Trading name</code>, <code>Industry (ANZSIC4) description</code>, <code>Number of seats</code>, <code>Seating type</code>, <code>CLUE small area</code>, <code>Latitude</code>, and <code>Longitude</code>. Data is sourced from the City of Melbourne’s Census of Land Use and Employment (CLUE). Available at: <a href="https://data.melbourne.vic.gov.au/explore/dataset/cafes-and-restaurants-with-seating-capacity" class="uri">https://data.melbourne.vic.gov.au/explore/dataset/cafes-and-restaurants-with-seating-capacity</a></p>
<p><strong>Source B – City of Melbourne: Bars and Pubs with Patron Capacity (2002–2024).</strong> This tabular dataset contains 5,304 observations across 12 columns. Each row records a bar or pub in a given census year with attributes including <code>Trading name</code>, <code>Number of patrons</code>, <code>CLUE small area</code>, <code>Latitude</code>, and <code>Longitude</code>. Available at: <a href="https://data.melbourne.vic.gov.au/explore/dataset/bars-pubs-patron-capacity" class="uri">https://data.melbourne.vic.gov.au/explore/dataset/bars-pubs-patron-capacity</a></p>
<p><strong>Source C – ABS Census General Community Profile G04 and G17 (2016, 2021).</strong> These are tabular datasets sourced from the Australian Bureau of Statistics Census DataPacks at Statistical Area Level 2 (SA2). G04 contains age-by-sex data; G17 (A, B, C) contains individual weekly income by age and sex. Each dataset has 464 rows (2016) or 524 rows (2021), corresponding to Victorian SA2 regions, and hundreds of columns representing demographic breakdowns. Available at: <a href="https://www.abs.gov.au/census/find-census-data/datapacks" class="uri">https://www.abs.gov.au/census/find-census-data/datapacks</a></p>
</section>
<section id="data-wrangling" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="data-wrangling"><span class="header-section-number">2.2</span> Data Wrangling</h2>
<p>The data wrangling process involved the following key steps:</p>
<p><strong>Source A &amp; B – Venue data:</strong> Source A uses a single ANZSIC code (4511, <em>Cafes and Restaurants</em>) that conflates two distinct venue types. To isolate cafés and exclude restaurants from the analysis, a name-based exclusion filter was applied to the trading name field. Rather than requiring names to contain café-positive keywords (e.g.&nbsp;“café”, “coffee”), which would incorrectly discard genuine cafés with non-descriptive names, the filter removes records whose names contain terms unambiguously associated with restaurants and non-café premises, including “restaurant”, “ristorante”, “pizzeria”, “sushi”, “ramen”, “brasserie”, “izakaya”, and compound ethnic cuisine qualifiers such as “Indian restaurant” and “Chinese restaurant”. Compound terms were used deliberately to avoid false positives (e.g.&nbsp;a venue named “Thai Basil Café” would not be excluded). This approach removed approximately 7,992 records (16% of ANZSIC 4511 entries) identified as clear restaurants, retaining 1,339 of 1,554 unique venues in the 2024 survey year. The remaining records may still include some casual dining venues with ambiguous names; this is acknowledged as a limitation of name-based classification in the absence of a finer ANZSIC subcategory. Takeaway food services (ANZSIC 4512) and accommodation were excluded by the ANZSIC filter. Source A also contains multiple rows per venue per year due to separate records for indoor, outdoor, and other seating types; these were aggregated to unique venue-year records by grouping on trading name, area, and year. The bars dataset required only deduplication, as each row already represents a distinct licensed premises.</p>
<p><strong>Source C – Census data:</strong> The G04 files (age distributions) and G17 files (weekly income) were each split across multiple CSV files (A, B, C) and required column-binding after filtering to the 19 SA2 regions within the City of Melbourne Local Government Area (identified by codes beginning with <code>2010</code>). A manual SA2-to-CLUE area crosswalk was constructed using ABS geographic correspondences to link census data to the City of Melbourne’s CLUE small area boundaries, enabling integration with Sources A and B. Weighted average weekly income was computed from the G17 income bracket counts using bracket midpoints as weights, excluding “not stated” responses from the denominator.</p>
</section>
<section id="data-checking" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="data-checking"><span class="header-section-number">2.3</span> Data Checking</h2>
<section id="missing-values" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="missing-values"><span class="header-section-number">2.3.1</span> Missing Values</h3>
<p>Missing values are confined entirely to the spatial coordinate columns (<code>Latitude</code> and <code>Longitude</code>). The cafés dataset has 377 records with missing coordinates, and the bars dataset has 20. All other fields, trading name, CLUE area, seating/patron capacity, are fully complete across both datasets. Records with missing coordinates are retained for count-based and temporal analyses but excluded from any spatial point mapping, as their area-level CLUE classification is still valid for aggregation purposes.</p>
</section>
<section id="temporal-consistency" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="temporal-consistency"><span class="header-section-number">2.3.2</span> Temporal Consistency</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-temporal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-temporal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cafes_vs_pubs_files/figure-html/fig-temporal-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-temporal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Number of unique café and bar venues recorded in each CLUE survey year from 2002 to 2024. Both datasets show continuous year-on-year coverage with no gaps. The dip in cafés around 2020–2021 reflects pandemic-related closures.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both datasets cover every survey year from 2002 to 2024 without gaps, confirming complete temporal coverage. Café counts grow steadily from 675 in 2002 to a peak of 1,385 in 2019, followed by a visible dip in 2020–2021 consistent with pandemic-related business closures, before recovering to 1,339 by 2024. Bar counts follow a similar upward trend, though more modest in scale, with no equivalent pandemic dip, likely reflecting pubs’ ability to pivot to takeaway liquor sales during lockdowns. No year contains implausibly few or many records, and no survey year is duplicated.</p>
</section>
<section id="venue-counts-by-area" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="venue-counts-by-area"><span class="header-section-number">2.3.3</span> Venue Counts by Area</h3>
<div class="cell">
<div id="tbl-area-counts" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-area-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Unique venue counts by CLUE small area (2024 survey year). Pub-to-café ratio is the number of bars and pubs divided by the number of cafés; a higher value indicates greater relative pub presence.
</figcaption>
<div aria-describedby="tbl-area-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Area</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Cafés</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Bars &amp; Pubs</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Total</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Pub-to-café ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Melbourne (CBD)</td>
<td style="text-align: right;">779</td>
<td style="text-align: right;">208</td>
<td style="text-align: right;">987</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Carlton</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">163</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Docklands</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">145</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southbank</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Melbourne</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Melbourne (Residential)</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Melbourne (Remainder)</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">East Melbourne</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kensington</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parkville</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Port Melbourne</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Yarra</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.17</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Table 1 confirms that Melbourne (CBD) accounts for the overwhelming majority of venues in both categories, with 779 cafés and 208 bars, far exceeding any other area. Carlton and Docklands are the next most venue-dense areas for cafés, while Southbank has a disproportionately high bar count (29) relative to its café count (110), giving it the second-highest pub-to-café ratio (0.26) after the CBD (0.27). Port Melbourne has no recorded bars in 2024. South Yarra, despite its well-known hospitality scene, has very few venues within the City of Melbourne boundary, reflecting that most of its venues fall just outside the CLUE survey area.</p>
</section>
</section>
</section>
<section id="data-exploration" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Exploration</h1>
<p>The exploration addresses the three research questions in sequence, building from spatial distribution to temporal trends and finally to demographic correlates.</p>
<section id="q1-how-does-the-distribution-of-cafés-and-pubs-vary-across-melbourne-areas" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="q1-how-does-the-distribution-of-cafés-and-pubs-vary-across-melbourne-areas"><span class="header-section-number">3.1</span> Q1: How does the distribution of cafés and pubs vary across Melbourne areas?</h2>
<p>A grouped horizontal bar chart is used here because the question asks about the <em>distribution</em> of two venue types across a set of named categorical areas. Horizontal orientation makes the area labels readable without rotation. Grouping the two bars side-by-side rather than stacking them allows direct length comparison between cafés and pubs within each area, which is the primary comparison of interest. Areas are ordered by total venue count so that the most active areas appear at the top.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-venue-counts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-venue-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cafes_vs_pubs_files/figure-html/fig-venue-counts-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-venue-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Number of unique cafés and pubs in each CLUE small area in 2024. Melbourne (CBD) dominates both venue types by a large margin, while areas like Kensington and Parkville have very few venues of either type.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-venue-counts" class="quarto-xref">Figure&nbsp;2</a> reveals a pronounced spatial concentration of both venue types. The Melbourne CBD alone accounts for the vast majority of venues in the dataset. Carlton and Southbank follow as the next most venue-dense areas. At the opposite extreme, West Melbourne (Industrial), Parkville, and Kensington contain very few venues of either type, reflecting their primarily industrial or institutional land uses.</p>
<p>A key visual pattern is that cafés consistently outnumber pubs and bars in every CLUE area, consistent with Melbourne’s strong coffee culture. However, the <em>degree</em> to which cafés dominate varies considerably by area, explored further in Question 2.</p>
</section>
<section id="q2-how-do-pub-to-café-ratios-differ-across-melbourne-areas-and-how-have-these-changed-over-time" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="q2-how-do-pub-to-café-ratios-differ-across-melbourne-areas-and-how-have-these-changed-over-time"><span class="header-section-number">3.2</span> Q2: How do pub-to-café ratios differ across Melbourne areas, and how have these changed over time?</h2>
<p>To move beyond raw counts and reveal <em>relative</em> pub presence, the pub-to-café ratio is computed for each area and displayed as a ranked horizontal bar chart. A single derived ratio variable reduces two counts to one comparable magnitude, making cross-area ordering immediately apparent through bar length, which encodes position on a common scale — the most effective channel for ordered quantitative data. A single uniform fill colour is used for all bars because the variable is continuous and ordinal colouring would impose an arbitrary category boundary. Only the top-ranked area is highlighted in orange to draw the reader’s eye without distorting the magnitude comparisons among the remaining bars.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ratio-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ratio-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cafes_vs_pubs_files/figure-html/fig-ratio-bar-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ratio-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Pub-to-café ratio (number of pubs divided by number of cafés) by CLUE small area in 2024. All bars use the same blue fill to represent a single continuous variable; Melbourne (CBD) is highlighted in orange as the area with the highest ratio.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-ratio-bar" class="quarto-xref">Figure&nbsp;3</a> shows that the pub-to-café ratio varies substantially across areas. The CBD and Southbank have the highest ratios (0.27 and 0.26 respectively), reflecting their role as entertainment precincts with large pub footprints. Residential areas such as Carlton, North Melbourne, and South Yarra have lower ratios, suggesting that café culture dominates in these neighbourhoods. This is consistent with the proposal that Melbourne’s coffee culture may be displacing pub culture in residential areas.</p>
<p>The temporal dimension of the question requires a line chart rather than a bar chart, as line charts are specifically suited to showing change over ordered time intervals. Six areas are selected to avoid overplotting while covering the range of area types: two high-ratio entertainment precincts (CBD and Southbank), one redeveloping precinct (Docklands), and three lower-ratio residential areas (Carlton, North Melbourne, South Yarra). Colour hue encodes area identity, which is a categorical distinction, consistent with the class guidance that hue is most effective for nominal groupings.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ratio-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ratio-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cafes_vs_pubs_files/figure-html/fig-ratio-time-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ratio-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Temporal trend of pub-to-café ratio for six selected CLUE areas from 2002 to 2024. A declining ratio indicates growing café dominance relative to pubs over time. Melbourne (CBD) and Southbank are highlighted in orange tones as the highest-ratio areas; remaining areas use blue tones.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-ratio-time" class="quarto-xref">Figure&nbsp;4</a> reveals a broadly declining pub-to-café ratio across most areas over the 22-year study period, with the most pronounced decline in Docklands and Southbank, two areas that have undergone major urban redevelopment. This trend is consistent with national findings on declining alcohol consumption among younger Australians <span class="citation" data-cites="aihw2024">[@aihw2024]</span>. The CBD ratio has remained relatively stable, likely reflecting its persistent role as an entertainment and nightlife precinct. Carlton shows a consistently low and declining ratio throughout the period, reflecting its long-established status as a café-centric suburb.</p>
</section>
<section id="q3-how-do-income-levels-and-age-distributions-relate-to-the-pub-to-café-ratio" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="q3-how-do-income-levels-and-age-distributions-relate-to-the-pub-to-café-ratio"><span class="header-section-number">3.3</span> Q3: How do income levels and age distributions relate to the pub-to-café ratio?</h2>
<p>Two scatterplots are presented as facets, each placing a demographic variable directly on the x-axis against the pub-to-café ratio on the y-axis. This follows the principle that position on a common scale is the most effective encoding for communicating ordered quantitative relationships, more so than colour or size, which were used in earlier spatial designs. Combining the two panels also allows direct visual comparison of how strongly each demographic variable relates to the ratio. Points are sized by total venue count so that small areas do not carry the same visual weight as the CBD; area names are labelled directly on each point.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-demo-facet" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-demo-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cafes_vs_pubs_files/figure-html/fig-demo-facet-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-demo-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Faceted scatterplot showing the relationship between the pub-to-café ratio (2024) and two demographic variables from the ABS 2021 Census: weighted average weekly income (left panel) and the proportion of residents aged 18–34 (right panel). Each point is a CLUE small area, sized by total venue count. A trend line with 95% confidence interval is fitted to each panel.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-demo-facet" class="quarto-xref">Figure&nbsp;5</a> shows a modest positive relationship in its left panel between average weekly income and the pub-to-café ratio. The CBD and Southbank (the two largest points) sit at the high end of both axes, suggesting that affluent, mixed-use entertainment precincts sustain a greater pub presence. Carlton is a notable outlier: despite having a relatively high average income (driven by proximity to the university and gentrification), it has one of the lowest pub-to-café ratios, reflecting its deep-rooted café culture. The right panel tells a different story: there is no meaningful positive relationship between the share of young adults (18–34) and the pub-to-café ratio. If anything, the trend is slightly negative. Carlton and Parkville, both areas with large student and young adult populations, cluster in the lower-right, combining high youth share with low pub prevalence. This is consistent with national evidence of declining alcohol consumption among younger Australians <span class="citation" data-cites="aihw2024">[@aihw2024]</span>, and suggests that the presence of young residents does not translate into greater pub dominance at the area level. Taken together, the two panels indicate that precinct character and income level are more relevant to pub prevalence than the age structure of the resident population.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusion</h1>
<p>This analysis explored the distribution and relative balance of cafés and pubs across the City of Melbourne’s CLUE small areas using venue data from 2002–2024 and ABS Census data from 2016 and 2021.</p>
<p>In response to <strong>Question 1</strong>, cafés and pubs are concentrated heavily in the Melbourne CBD, with Carlton, Docklands, and Southbank as secondary clusters. Cafés consistently outnumber pubs in every CLUE area, reflecting Melbourne’s strong coffee culture.</p>
<p>Regarding <strong>Question 2</strong>, the pub-to-café ratio has declined across most areas over the 22-year study period, most dramatically in Docklands and Southbank. This temporal trend is consistent with a city-wide cultural shift towards café culture, aligning with national evidence of declining alcohol consumption in younger generations <span class="citation" data-cites="aihw2024">[@aihw2024]</span>.</p>
<p>For <strong>Question 3</strong>, the faceted scatterplot revealed that pub dominance is more strongly associated with higher-income entertainment precincts than with areas that have large young adult populations. Carlton and Parkville, both youth-heavy, have among the lowest pub-to-café ratios, while the CBD and Southbank combine high income with high pub presence. This challenges the intuitive assumption that younger residents drive pub culture, and instead points to the role of precinct character and income level.</p>
<p>The analysis was limited by the coarse spatial granularity of the CLUE area system (13 zones) and by the approximate SA2-to-CLUE crosswalk required to link census data. Future work could incorporate finer spatial units and foot traffic data to better account for non-resident demand.</p>
</section>
<section id="reflection" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Reflection</h1>
<p>This project reinforced several key lessons about data visualisation and exploratory analysis. First, the choice of visual encoding matters enormously: switching from a raw count bar chart (<a href="#fig-venue-counts" class="quarto-xref">Figure&nbsp;2</a>) to a ratio visualisation revealed a completely different spatial pattern, highlighting how the framing of a question shapes what we see. Second, the faceted scatterplot for Question 3 was chosen over spatial maps because the core question is about the relationship between demographics and the ratio, and position on a common scale encodes that relationship more precisely than colour or size on a map. This reflects the principle that just because data has a geographic component does not mean it should always be mapped.</p>
<p>In hindsight, using proper polygon boundary data (ABS SA2 shapefiles or City of Melbourne CLUE area boundaries) to produce choropleth maps would have made the spatial encoding even more precise and visually compelling. I would also have liked to explore venue density per capita rather than raw counts, which would account for the very different resident populations across areas. Finally, the name-based café filter, while defensible, could be improved with a supervised classification approach trained on a manually labelled sample of venue names.</p>
</section>
<section id="bibliography" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Bibliography</h1>
<div id="refs" role="list">

</div>
<hr>
</section>
<section id="generative-ai-declaration" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Generative AI Declaration</h1>
<p><a href="https://chatgpt.com/share/69e9badd-85c0-839a-82c0-d119188d199b">Link 1</a> helped me write the R code to join ABS data G04 &amp; G17</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Cafés Vs. Pubs in Melbourne"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Ibtesam Ifaz"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 2</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-width: 7</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-height: 4.5</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: false</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>**Project Title:** Cafés Vs. Pubs in Melbourne</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Melbourne is internationally recognised as one of the world's great coffee cities, yet it also maintains a deeply ingrained pub culture. Recent research indicates that younger Australians are drinking less alcohol than previous generations <span class="co">[</span><span class="ot">@aihw2024</span><span class="co">]</span>, which raises an interesting question about how this cultural shift may be reflected in the physical landscape of Melbourne's hospitality sector. This project explores the distribution of cafés and pubs across the City of Melbourne's defined local areas, examining how these venues are distributed, how their relative proportions have changed over time, and whether the balance between café and pub culture relates to the socioeconomic and demographic character of different neighbourhoods.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>The findings are relevant to a broad range of audiences: potential hospitality business owners and investors seeking to identify underserved markets, urban planners and local government officials interested in how venues shape neighbourhood character, and researchers studying the relationship between place-based consumption patterns and demographics.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>**Questions addressed in this report:**</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>How does the distribution of cafés and pubs vary across different areas of Melbourne?</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>How do pub-to-café ratios differ across Melbourne areas, and how have these ratios changed over time?</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>How do income levels and age distributions relate to the pub-to-café ratio across different areas?</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Wrangling and Checking</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Sources</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>Three data sources were used in this analysis:</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>**Source A – City of Melbourne: Cafés and Restaurants with Seating Capacity (2002–2024).** This tabular dataset contains 66,356 observations across 15 columns. Each row represents a specific seating-type record for a food/beverage venue in a given census year. Key attributes include <span class="in">`Trading name`</span>, <span class="in">`Industry (ANZSIC4) description`</span>, <span class="in">`Number of seats`</span>, <span class="in">`Seating type`</span>, <span class="in">`CLUE small area`</span>, <span class="in">`Latitude`</span>, and <span class="in">`Longitude`</span>. Data is sourced from the City of Melbourne's Census of Land Use and Employment (CLUE). Available at: <span class="ot">&lt;https://data.melbourne.vic.gov.au/explore/dataset/cafes-and-restaurants-with-seating-capacity&gt;</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>**Source B – City of Melbourne: Bars and Pubs with Patron Capacity (2002–2024).** This tabular dataset contains 5,304 observations across 12 columns. Each row records a bar or pub in a given census year with attributes including <span class="in">`Trading name`</span>, <span class="in">`Number of patrons`</span>, <span class="in">`CLUE small area`</span>, <span class="in">`Latitude`</span>, and <span class="in">`Longitude`</span>. Available at: <span class="ot">&lt;https://data.melbourne.vic.gov.au/explore/dataset/bars-pubs-patron-capacity&gt;</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>**Source C – ABS Census General Community Profile G04 and G17 (2016, 2021).** These are tabular datasets sourced from the Australian Bureau of Statistics Census DataPacks at Statistical Area Level 2 (SA2). G04 contains age-by-sex data; G17 (A, B, C) contains individual weekly income by age and sex. Each dataset has 464 rows (2016) or 524 rows (2021), corresponding to Victorian SA2 regions, and hundreds of columns representing demographic breakdowns. Available at: <span class="ot">&lt;https://www.abs.gov.au/census/find-census-data/datapacks&gt;</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Wrangling</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load-data}</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Load raw data ──────────────────────────────────────────────────────────────</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>cafes_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/cafes_restaurants_seating.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>bars_raw  <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/bars_pubs_patron_capacity.csv"</span>,  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="co"># ABS Census files</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>g04a_21 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G04A_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>g04b_21 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G04B_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>g17a_21 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G17A_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>g17b_21 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G17B_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>g17c_21 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G17C_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>g04a_16 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2016Census_G04A_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>g04b_16 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2016Census_G04B_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>g17a_16 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2016Census_G17A_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>g17b_16 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2016Census_G17B_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>g17c_16 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2016Census_G17C_VIC_SA2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="in">```{r wrangle-venues}</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 1: Filter to ANZSIC 4511, then exclude clear restaurant entries ───────</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="co"># Source A uses ANZSIC 4511 "Cafes and Restaurants", a single code that</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="co"># conflates two distinct venue types. To isolate cafés, we apply a</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="co"># name-based exclusion filter, removing records whose trading name contains</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="co"># terms unambiguously associated with restaurants (e.g. "Restaurant",</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="co"># "Ristorante", "Sushi", "Ramen", "Pizzeria", "Brasserie") rather than</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="co"># café-style premises. An exclusion approach is deliberately chosen over</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="co"># an inclusion approach: requiring a name to contain "cafe" or "coffee"</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="co"># would incorrectly discard many genuine cafés with non-descriptive names</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="co"># (e.g. "Brunetti", "Patricia"), whereas excluding explicit restaurant</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="co"># terminology preserves these while removing records that are clearly</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="co"># out of scope. Ethnic cuisine qualifiers (e.g. "Indian Restaurant",</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="co"># "Chinese Restaurant") are included as compound terms to avoid</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="co"># accidentally dropping venues like "Thai Basil Café".</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>restaurant_excl <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>  <span class="st">"restaurant"</span>, <span class="st">"ristorante"</span>, <span class="st">"restorante"</span>, <span class="st">"trattoria"</span>, <span class="st">"osteria"</span>,</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pizzeria"</span>, <span class="st">"pizza"</span>, <span class="st">"sushi"</span>, <span class="st">"ramen"</span>, <span class="st">"noodle"</span>, <span class="st">"yum cha"</span>, <span class="st">"dim sum"</span>,</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>  <span class="st">"izakaya"</span>, <span class="st">"teppanyaki"</span>, <span class="st">"steakhouse"</span>, <span class="st">"steak house"</span>, <span class="st">"chophouse"</span>,</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>  <span class="st">"brasserie"</span>, <span class="st">"tavern"</span>, <span class="st">"pub "</span>, <span class="st">"burger"</span>, <span class="st">"kebab"</span>,</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>  <span class="st">"indian restaurant"</span>, <span class="st">"chinese restaurant"</span>, <span class="st">"thai restaurant"</span>,</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>  <span class="st">"japanese restaurant"</span>, <span class="st">"korean restaurant"</span>, <span class="st">"mexican restaurant"</span>,</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>  <span class="st">"vietnamese restaurant"</span>, <span class="st">"greek restaurant"</span>, <span class="st">"italian restaurant"</span>,</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>  <span class="st">"seafood restaurant"</span>, <span class="st">"french restaurant"</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>excl_pattern <span class="ot">&lt;-</span> <span class="fu">paste</span>(restaurant_excl, <span class="at">collapse =</span> <span class="st">"|"</span>)</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>cafes_clean <span class="ot">&lt;-</span> cafes_raw <span class="sc">%&gt;%</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Industry (ANZSIC4) description</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Cafes and Restaurants"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(<span class="fu">str_to_lower</span>(<span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>), excl_pattern)) <span class="sc">%&gt;%</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">area =</span> <span class="st">`</span><span class="at">CLUE small area</span><span class="st">`</span>, <span class="at">year =</span> <span class="st">`</span><span class="at">Census year</span><span class="st">`</span>,</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>         <span class="at">seats =</span> <span class="st">`</span><span class="at">Number of seats</span><span class="st">`</span>, <span class="at">lat =</span> Latitude, <span class="at">lon =</span> Longitude) <span class="sc">%&gt;%</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, area, <span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>, seats, lat, lon)</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 2: Bars dataset already contains only licensed premises ───────────────</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>bars_clean <span class="ot">&lt;-</span> bars_raw <span class="sc">%&gt;%</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">area =</span> <span class="st">`</span><span class="at">CLUE small area</span><span class="st">`</span>, <span class="at">year =</span> <span class="st">`</span><span class="at">Census year</span><span class="st">`</span>,</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>         <span class="at">patrons =</span> <span class="st">`</span><span class="at">Number of patrons</span><span class="st">`</span>, <span class="at">lat =</span> Latitude, <span class="at">lon =</span> Longitude) <span class="sc">%&gt;%</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, area, <span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>, patrons, lat, lon)</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 3: For venue counts by area-year, collapse seating rows to unique</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="co">#            venues (a venue may have multiple seating-type rows per year) ──────</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>cafes_venues <span class="ot">&lt;-</span> cafes_clean <span class="sc">%&gt;%</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, area, <span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>, lat, lon) <span class="sc">%&gt;%</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_seats =</span> <span class="fu">sum</span>(seats, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>bars_venues <span class="ot">&lt;-</span> bars_clean <span class="sc">%&gt;%</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(year, area, <span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r wrangle-census}</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 4: Combine G04 A+B for both census years, filter to Melbourne SA2s ───</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="co"># Melbourne City LGA SA2 codes start with "2010"</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>melb_sa2_codes_21 <span class="ot">&lt;-</span> g04a_21 <span class="sc">%&gt;%</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_starts</span>(<span class="fu">as.character</span>(SA2_CODE_2021), <span class="st">"2010"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(SA2_CODE_2021)</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>melb_sa2_codes_16 <span class="ot">&lt;-</span> g04a_16 <span class="sc">%&gt;%</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_starts</span>(<span class="fu">as.character</span>(SA2_MAINCODE_2016), <span class="st">"2010"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(SA2_MAINCODE_2016)</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="co"># Age group totals (persons, all ages) from G04A and G04B</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="co"># We want: 18-34 share (young adults) and 55+ share (older adults)</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>get_age_groups <span class="ot">&lt;-</span> <span class="cf">function</span>(g04a, g04b, sa2_col, codes) {</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>    g04a <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.data[[sa2_col]] <span class="sc">%in%</span> codes) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">all_of</span>(sa2_col)),</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>    g04a <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.data[[sa2_col]] <span class="sc">%in%</span> codes) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">all_of</span>(sa2_col)),</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>    g04b <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.data[[sa2_col]] <span class="sc">%in%</span> codes) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">all_of</span>(sa2_col))</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Age 18-34: individual year columns live in G04A</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>  age_18_34_cols <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"Age_yr_"</span>, <span class="dv">18</span><span class="sc">:</span><span class="dv">34</span>, <span class="st">"_P"</span>)</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Age 55+: grouped band columns in G04B (actual names confirmed from data)</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>  age_55_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Age_yr_55_59_P"</span>, <span class="st">"Age_yr_60_64_P"</span>, <span class="st">"Age_yr_65_69_P"</span>,</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Age_yr_70_74_P"</span>, <span class="st">"Age_yr_75_79_P"</span>, <span class="st">"Age_yr_80_84_P"</span>,</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Age_yr_85_89_P"</span>, <span class="st">"Age_yr_90_94_P"</span>, <span class="st">"Age_yr_95_99_P"</span>,</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Age_yr_100_yr_over_P"</span>)</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Total population column is "Tot_P" (in G04B)</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>  age_18_34_cols_avail <span class="ot">&lt;-</span> <span class="fu">intersect</span>(age_18_34_cols, <span class="fu">names</span>(df))</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>  age_55_cols_avail    <span class="ot">&lt;-</span> <span class="fu">intersect</span>(age_55_cols, <span class="fu">names</span>(df))</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>      <span class="at">pop_18_34  =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">all_of</span>(age_18_34_cols_avail)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>      <span class="at">pop_55plus =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">all_of</span>(age_55_cols_avail)),    <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>      <span class="at">pop_total  =</span> Tot_P</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="at">sa2 =</span> <span class="fu">all_of</span>(sa2_col), pop_18_34, pop_55plus, pop_total)</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>age_21 <span class="ot">&lt;-</span> <span class="fu">get_age_groups</span>(g04a_21, g04b_21, <span class="st">"SA2_CODE_2021"</span>, melb_sa2_codes_21)</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>age_16 <span class="ot">&lt;-</span> <span class="fu">get_age_groups</span>(g04a_16, g04b_16, <span class="st">"SA2_MAINCODE_2016"</span>, melb_sa2_codes_16)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 5: Compute weighted median weekly income from G17 A+B+C ──────────────</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="co"># Income brackets (weekly $): use midpoints</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>income_midpoints <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_Neg_Nil_income_Tot =</span> <span class="dv">0</span>,</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_1_149_Tot          =</span> <span class="dv">75</span>,</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_150_299_Tot        =</span> <span class="dv">225</span>,</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_300_399_Tot        =</span> <span class="dv">350</span>,</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_400_499_Tot        =</span> <span class="dv">450</span>,</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_500_649_Tot        =</span> <span class="dv">575</span>,</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_650_799_Tot        =</span> <span class="dv">725</span>,</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_800_999_Tot        =</span> <span class="dv">900</span>,</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_1000_1249_Tot      =</span> <span class="dv">1125</span>,</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_1250_1499_Tot      =</span> <span class="dv">1375</span>,</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_1500_1749_Tot      =</span> <span class="dv">1625</span>,</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_1750_1999_Tot      =</span> <span class="dv">1875</span>,</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_2000_2999_Tot      =</span> <span class="dv">2500</span>,</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_3000_3499_Tot      =</span> <span class="dv">3250</span>,</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_3500_more_Tot      =</span> <span class="dv">4000</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>compute_income <span class="ot">&lt;-</span> <span class="cf">function</span>(g17a, g17b, g17c, sa2_col, codes) {</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Merge the three income files</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> g17a <span class="sc">%&gt;%</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(.data[[sa2_col]] <span class="sc">%in%</span> codes) <span class="sc">%&gt;%</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(g17b <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.data[[sa2_col]] <span class="sc">%in%</span> codes), <span class="at">by =</span> sa2_col) <span class="sc">%&gt;%</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(g17c <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.data[[sa2_col]] <span class="sc">%in%</span> codes), <span class="at">by =</span> sa2_col)</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>  bkt_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(income_midpoints)</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>  bkt_avail <span class="ot">&lt;-</span> <span class="fu">intersect</span>(bkt_cols, <span class="fu">names</span>(df))</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>      <span class="at">weighted_income =</span> <span class="fu">rowSums</span>(</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>        <span class="fu">across</span>(<span class="fu">all_of</span>(bkt_avail), <span class="sc">~</span> .x <span class="sc">*</span> income_midpoints[<span class="fu">cur_column</span>()]),</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>        <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">/</span> <span class="fu">rowSums</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(bkt_avail)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="at">sa2 =</span> <span class="fu">all_of</span>(sa2_col), weighted_income)</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>income_21 <span class="ot">&lt;-</span> <span class="fu">compute_income</span>(g17a_21, g17b_21, g17c_21, <span class="st">"SA2_CODE_2021"</span>, melb_sa2_codes_21)</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>income_16 <span class="ot">&lt;-</span> <span class="fu">compute_income</span>(g17a_16, g17b_16, g17c_16, <span class="st">"SA2_MAINCODE_2016"</span>, melb_sa2_codes_16)</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 6: Manual SA2-to-CLUE area mapping ────────────────────────────────────</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="co"># Inner Melbourne SA2s map approximately to CLUE small areas as below.</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="co"># This crosswalk is derived from ABS geographic correspondences and</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="co"># City of Melbourne boundary definitions.</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>sa2_clue_map <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>sa2,        <span class="sc">~</span>clue_area,</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011001</span>L,  <span class="st">"Carlton"</span>,</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011002</span>L,  <span class="st">"Docklands"</span>,</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011005</span>L,  <span class="st">"East Melbourne"</span>,</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011006</span>L,  <span class="st">"Kensington"</span>,</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011007</span>L,  <span class="st">"Melbourne (CBD)"</span>,</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011008</span>L,  <span class="st">"Melbourne (Remainder)"</span>,</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011481</span>L,  <span class="st">"North Melbourne"</span>,</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011482</span>L,  <span class="st">"Parkville"</span>,</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011483</span>L,  <span class="st">"Port Melbourne"</span>,</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201011484</span>L,  <span class="st">"South Yarra"</span>,</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201021009</span>L,  <span class="st">"Southbank"</span>,</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201021010</span>L,  <span class="st">"West Melbourne (Residential)"</span>,</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201021011</span>L,  <span class="st">"West Melbourne (Industrial)"</span>,</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201021012</span>L,  <span class="st">"Melbourne (CBD)"</span>,   <span class="co"># city north</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201031013</span>L,  <span class="st">"Carlton"</span>,           <span class="co"># Carlton North</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201031014</span>L,  <span class="st">"Fitzroy"</span>,</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201031015</span>L,  <span class="st">"Fitzroy North"</span>,</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201031016</span>L,  <span class="st">"Collingwood"</span>,</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>  <span class="dv">201031017</span>L,  <span class="st">"Richmond"</span></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="co"># Join census data to CLUE mapping</span></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: weighted.mean must use the per-SA2 pop_total BEFORE it is summed,</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="co"># so we compute it in a separate summarise step.</span></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>census_21_raw <span class="ot">&lt;-</span> age_21 <span class="sc">%&gt;%</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(income_21, <span class="at">by =</span> <span class="st">"sa2"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(sa2_clue_map <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">sa2 =</span> <span class="fu">as.integer</span>(sa2)), <span class="at">by =</span> <span class="st">"sa2"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(clue_area))</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>census_21 <span class="ot">&lt;-</span> census_21_raw <span class="sc">%&gt;%</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clue_area) <span class="sc">%&gt;%</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_18_34       =</span> <span class="fu">sum</span>(pop_18_34,  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_55plus      =</span> <span class="fu">sum</span>(pop_55plus, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_total       =</span> <span class="fu">sum</span>(pop_total,  <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Drop NAs from both x and w together before taking weighted mean</span></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>    <span class="at">weighted_income =</span> {</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>      x <span class="ot">&lt;-</span> weighted_income; w <span class="ot">&lt;-</span> pop_total</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>      keep <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">is.na</span>(x) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(w)</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="fu">sum</span>(keep) <span class="sc">==</span> <span class="dv">0</span>) <span class="cn">NA_real_</span> <span class="cf">else</span> <span class="fu">weighted.mean</span>(x[keep], <span class="at">w =</span> w[keep])</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_18_34   =</span> pop_18_34  <span class="sc">/</span> pop_total <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_55plus  =</span> pop_55plus <span class="sc">/</span> pop_total <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>    <span class="at">census_year =</span> <span class="dv">2021</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="in">```{r build-ratio-data}</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Step 7: Build venue counts by CLUE area and year ──────────────────────────</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>cafe_counts <span class="ot">&lt;-</span> cafes_venues <span class="sc">%&gt;%</span></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, area) <span class="sc">%&gt;%</span></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_cafes =</span> <span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>bar_counts <span class="ot">&lt;-</span> bars_venues <span class="sc">%&gt;%</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, area) <span class="sc">%&gt;%</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_bars =</span> <span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>venue_ratio <span class="ot">&lt;-</span> cafe_counts <span class="sc">%&gt;%</span></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(bar_counts, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"area"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(<span class="fu">list</span>(<span class="at">n_cafes =</span> <span class="dv">0</span>, <span class="at">n_bars =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_venues   =</span> n_cafes <span class="sc">+</span> n_bars,</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>    <span class="at">ratio_bar_cafe =</span> n_bars <span class="sc">/</span> <span class="fu">ifelse</span>(n_cafes <span class="sc">==</span> <span class="dv">0</span>, <span class="cn">NA_real_</span>, n_cafes),</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_bars       =</span> n_bars <span class="sc">/</span> total_venues <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(area))</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="co"># Latest year snapshot (2024)</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>venue_2024 <span class="ot">&lt;-</span> venue_ratio <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2024</span>)</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a><span class="co"># Joined with census 2021</span></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>venue_census <span class="ot">&lt;-</span> venue_2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(census_21, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"area"</span> <span class="ot">=</span> <span class="st">"clue_area"</span>))</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>The data wrangling process involved the following key steps:</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>**Source A &amp; B – Venue data:** Source A uses a single ANZSIC code (4511, *Cafes and Restaurants*) that conflates two distinct venue types. To isolate cafés and exclude restaurants from the analysis, a name-based exclusion filter was applied to the trading name field. Rather than requiring names to contain café-positive keywords (e.g. "café", "coffee"), which would incorrectly discard genuine cafés with non-descriptive names, the filter removes records whose names contain terms unambiguously associated with restaurants and non-café premises, including "restaurant", "ristorante", "pizzeria", "sushi", "ramen", "brasserie", "izakaya", and compound ethnic cuisine qualifiers such as "Indian restaurant" and "Chinese restaurant". Compound terms were used deliberately to avoid false positives (e.g. a venue named "Thai Basil Café" would not be excluded). This approach removed approximately 7,992 records (16% of ANZSIC 4511 entries) identified as clear restaurants, retaining 1,339 of 1,554 unique venues in the 2024 survey year. The remaining records may still include some casual dining venues with ambiguous names; this is acknowledged as a limitation of name-based classification in the absence of a finer ANZSIC subcategory. Takeaway food services (ANZSIC 4512) and accommodation were excluded by the ANZSIC filter. Source A also contains multiple rows per venue per year due to separate records for indoor, outdoor, and other seating types; these were aggregated to unique venue-year records by grouping on trading name, area, and year. The bars dataset required only deduplication, as each row already represents a distinct licensed premises.</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>**Source C – Census data:** The G04 files (age distributions) and G17 files (weekly income) were each split across multiple CSV files (A, B, C) and required column-binding after filtering to the 19 SA2 regions within the City of Melbourne Local Government Area (identified by codes beginning with <span class="in">`2010`</span>). A manual SA2-to-CLUE area crosswalk was constructed using ABS geographic correspondences to link census data to the City of Melbourne's CLUE small area boundaries, enabling integration with Sources A and B. Weighted average weekly income was computed from the G17 income bracket counts using bracket midpoints as weights, excluding "not stated" responses from the denominator.</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Checking</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="fu">### Missing Values</span></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>Missing values are confined entirely to the spatial coordinate columns (<span class="in">`Latitude`</span> and <span class="in">`Longitude`</span>). The cafés dataset has 377 records with missing coordinates, and the bars dataset has 20. All other fields, trading name, CLUE area, seating/patron capacity, are fully complete across both datasets. Records with missing coordinates are retained for count-based and temporal analyses but excluded from any spatial point mapping, as their area-level CLUE classification is still valid for aggregation purposes.</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="fu">### Temporal Consistency</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-temporal, fig.cap="Number of unique café and bar venues recorded in each CLUE survey year from 2002 to 2024. Both datasets show continuous year-on-year coverage with no gaps. The dip in cafés around 2020--2021 reflects pandemic-related closures.", fig.height=4}</span></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="co"># Unique venue counts per year for both datasets</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>cafe_year <span class="ot">&lt;-</span> cafes_venues <span class="sc">%&gt;%</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="st">"Cafés"</span>)</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>bar_year <span class="ot">&lt;-</span> bars_venues <span class="sc">%&gt;%</span></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(<span class="st">`</span><span class="at">Trading name</span><span class="st">`</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="st">"Bars &amp; Pubs"</span>)</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(cafe_year, bar_year) <span class="sc">%&gt;%</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n, <span class="at">colour =</span> type, <span class="at">group =</span> type)) <span class="sc">+</span></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Cafés"</span> <span class="ot">=</span> <span class="st">"#2196F3"</span>, <span class="st">"Bars &amp; Pubs"</span> <span class="ot">=</span> <span class="st">"#E65100"</span>)) <span class="sc">+</span></span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">2002</span>, <span class="dv">2024</span>, <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Survey year"</span>, <span class="at">y =</span> <span class="st">"Unique venue count"</span>,</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="cn">NULL</span>,</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Temporal coverage, unique venues per year (2002–2024)"</span>) <span class="sc">+</span></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a>Both datasets cover every survey year from 2002 to 2024 without gaps, confirming complete temporal coverage. Café counts grow steadily from 675 in 2002 to a peak of 1,385 in 2019, followed by a visible dip in 2020–2021 consistent with pandemic-related business closures, before recovering to 1,339 by 2024. Bar counts follow a similar upward trend, though more modest in scale, with no equivalent pandemic dip, likely reflecting pubs' ability to pivot to takeaway liquor sales during lockdowns. No year contains implausibly few or many records, and no survey year is duplicated.</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a><span class="fu">### Venue Counts by Area</span></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-area-counts}</span></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a><span class="co"># Build table of cafe and bar counts per area for 2024</span></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>tbl_counts <span class="ot">&lt;-</span> venue_2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">Area =</span> area, Cafés <span class="ot">=</span> n_cafes, <span class="st">`</span><span class="at">Bars &amp; Pubs</span><span class="st">`</span> <span class="ot">=</span> n_bars) <span class="sc">%&gt;%</span></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Total =</span> Cafés <span class="sc">+</span> <span class="st">`</span><span class="at">Bars &amp; Pubs</span><span class="st">`</span>,</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Pub-to-café ratio</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="st">`</span><span class="at">Bars &amp; Pubs</span><span class="st">`</span> <span class="sc">/</span> <span class="fu">ifelse</span>(Cafés <span class="sc">==</span> <span class="dv">0</span>, <span class="cn">NA</span>, Cafés), <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total))</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tbl_counts,</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Unique venue counts by CLUE small area (2024 survey year). Pub-to-café ratio is the number of bars and pubs divided by the number of cafés; a higher value indicates greater relative pub presence."</span>,</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a>      <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>      <span class="at">linesep  =</span> <span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hold_position"</span>),</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>                <span class="at">font_size =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>Table 1 confirms that Melbourne (CBD) accounts for the overwhelming majority of venues in both categories, with 779 cafés and 208 bars, far exceeding any other area. Carlton and Docklands are the next most venue-dense areas for cafés, while Southbank has a disproportionately high bar count (29) relative to its café count (110), giving it the second-highest pub-to-café ratio (0.26) after the CBD (0.27). Port Melbourne has no recorded bars in 2024. South Yarra, despite its well-known hospitality scene, has very few venues within the City of Melbourne boundary, reflecting that most of its venues fall just outside the CLUE survey area.</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Exploration</span></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>The exploration addresses the three research questions in sequence, building from spatial distribution to temporal trends and finally to demographic correlates.</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q1: How does the distribution of cafés and pubs vary across Melbourne areas?</span></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>A grouped horizontal bar chart is used here because the question asks about the *distribution* of two venue types across a set of named categorical areas. Horizontal orientation makes the area labels readable without rotation. Grouping the two bars side-by-side rather than stacking them allows direct length comparison between cafés and pubs within each area, which is the primary comparison of interest. Areas are ordered by total venue count so that the most active areas appear at the top.</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-venue-counts, fig.cap="Number of unique cafés and pubs in each CLUE small area in 2024. Melbourne (CBD) dominates both venue types by a large margin, while areas like Kensington and Parkville have very few venues of either type.", fig.height=5}</span></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>venue_2024_long <span class="ot">&lt;-</span> venue_2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(area, n_cafes, n_bars) <span class="sc">%&gt;%</span></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(n_cafes, n_bars),</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"type"</span>, <span class="at">values_to =</span> <span class="st">"count"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="fu">recode</span>(type, <span class="at">n_cafes =</span> <span class="st">"Cafés"</span>, <span class="at">n_bars =</span> <span class="st">"Pubs &amp; Bars"</span>),</span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a>         <span class="at">type =</span> <span class="fu">factor</span>(type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Pubs &amp; Bars"</span>, <span class="st">"Cafés"</span>)))</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>area_order <span class="ot">&lt;-</span> venue_2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total =</span> n_cafes <span class="sc">+</span> n_bars) <span class="sc">%&gt;%</span></span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total)) <span class="sc">%&gt;%</span></span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(area)</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>venue_2024_long <span class="sc">%&gt;%</span></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area =</span> <span class="fu">factor</span>(area, <span class="at">levels =</span> <span class="fu">rev</span>(area_order))) <span class="sc">%&gt;%</span></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> count, <span class="at">y =</span> area, <span class="at">fill =</span> type)) <span class="sc">+</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Cafés"</span> <span class="ot">=</span> <span class="st">"#2196F3"</span>, <span class="st">"Pubs &amp; Bars"</span> <span class="ot">=</span> <span class="st">"#E65100"</span>)) <span class="sc">+</span></span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of unique venues (2024)"</span>,</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="cn">NULL</span>,</span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Venue counts by CLUE small area (2024)"</span></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor   =</span> <span class="fu">element_blank</span>()</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a>@fig-venue-counts reveals a pronounced spatial concentration of both venue types. The Melbourne CBD alone accounts for the vast majority of venues in the dataset. Carlton and Southbank follow as the next most venue-dense areas. At the opposite extreme, West Melbourne (Industrial), Parkville, and Kensington contain very few venues of either type, reflecting their primarily industrial or institutional land uses.</span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a>A key visual pattern is that cafés consistently outnumber pubs and bars in every CLUE area, consistent with Melbourne's strong coffee culture. However, the *degree* to which cafés dominate varies considerably by area, explored further in Question 2.</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q2: How do pub-to-café ratios differ across Melbourne areas, and how have these changed over time?</span></span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a>To move beyond raw counts and reveal *relative* pub presence, the pub-to-café ratio is computed for each area and displayed as a ranked horizontal bar chart. A single derived ratio variable reduces two counts to one comparable magnitude, making cross-area ordering immediately apparent through bar length, which encodes position on a common scale — the most effective channel for ordered quantitative data. A single uniform fill colour is used for all bars because the variable is continuous and ordinal colouring would impose an arbitrary category boundary. Only the top-ranked area is highlighted in orange to draw the reader's eye without distorting the magnitude comparisons among the remaining bars.</span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-ratio-bar, fig.cap="Pub-to-café ratio (number of pubs divided by number of cafés) by CLUE small area in 2024. All bars use the same blue fill to represent a single continuous variable; Melbourne (CBD) is highlighted in orange as the area with the highest ratio.", fig.height=4}</span></span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify the single highest-ratio area to highlight</span></span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>top_area <span class="ot">&lt;-</span> venue_2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ratio_bar_cafe)) <span class="sc">%&gt;%</span></span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(ratio_bar_cafe, <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(area)</span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a>venue_2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ratio_bar_cafe)) <span class="sc">%&gt;%</span></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area      =</span> <span class="fu">fct_reorder</span>(area, ratio_bar_cafe),</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a>         <span class="at">highlight =</span> area <span class="sc">==</span> top_area) <span class="sc">%&gt;%</span></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ratio_bar_cafe, <span class="at">y =</span> area, <span class="at">fill =</span> highlight)) <span class="sc">+</span></span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"#90CAF9"</span>, <span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"#E65100"</span>),</span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a>                    <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Pubs per café (ratio)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Pub-to-café ratio by area (2024)"</span>) <span class="sc">+</span></span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a>@fig-ratio-bar shows that the pub-to-café ratio varies substantially across areas. The CBD and Southbank have the highest ratios (0.27 and 0.26 respectively), reflecting their role as entertainment precincts with large pub footprints. Residential areas such as Carlton, North Melbourne, and South Yarra have lower ratios, suggesting that café culture dominates in these neighbourhoods. This is consistent with the proposal that Melbourne's coffee culture may be displacing pub culture in residential areas.</span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a>The temporal dimension of the question requires a line chart rather than a bar chart, as line charts are specifically suited to showing change over ordered time intervals. Six areas are selected to avoid overplotting while covering the range of area types: two high-ratio entertainment precincts (CBD and Southbank), one redeveloping precinct (Docklands), and three lower-ratio residential areas (Carlton, North Melbourne, South Yarra). Colour hue encodes area identity, which is a categorical distinction, consistent with the class guidance that hue is most effective for nominal groupings.</span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-ratio-time, fig.cap="Temporal trend of pub-to-café ratio for six selected CLUE areas from 2002 to 2024. A declining ratio indicates growing café dominance relative to pubs over time. Melbourne (CBD) and Southbank are highlighted in orange tones as the highest-ratio areas; remaining areas use blue tones.", fig.height=5}</span></span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a>focus_areas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Melbourne (CBD)"</span>, <span class="st">"Carlton"</span>, <span class="st">"Southbank"</span>,</span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"North Melbourne"</span>, <span class="st">"South Yarra"</span>, <span class="st">"Docklands"</span>)</span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a><span class="co"># Consistent palette: orange family for high-ratio entertainment precincts,</span></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a><span class="co"># blue family for lower-ratio residential areas, echoing the Q1/Q2 colour logic</span></span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>area_colours <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Melbourne (CBD)"</span> <span class="ot">=</span> <span class="st">"#E65100"</span>,</span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Southbank"</span>       <span class="ot">=</span> <span class="st">"#FF8F00"</span>,</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Docklands"</span>       <span class="ot">=</span> <span class="st">"#FFB300"</span>,</span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Carlton"</span>         <span class="ot">=</span> <span class="st">"#1565C0"</span>,</span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a>  <span class="st">"North Melbourne"</span> <span class="ot">=</span> <span class="st">"#1E88E5"</span>,</span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a>  <span class="st">"South Yarra"</span>     <span class="ot">=</span> <span class="st">"#90CAF9"</span></span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a>venue_ratio <span class="sc">%&gt;%</span></span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(area <span class="sc">%in%</span> focus_areas) <span class="sc">%&gt;%</span></span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> ratio_bar_cafe, <span class="at">colour =</span> area)) <span class="sc">+</span></span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> area_colours, <span class="at">name =</span> <span class="st">"Area"</span>) <span class="sc">+</span></span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Pubs per café (ratio)"</span>,</span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Pub-to-café ratio over time (selected areas)"</span>) <span class="sc">+</span></span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a>@fig-ratio-time reveals a broadly declining pub-to-café ratio across most areas over the 22-year study period, with the most pronounced decline in Docklands and Southbank, two areas that have undergone major urban redevelopment. This trend is consistent with national findings on declining alcohol consumption among younger Australians <span class="co">[</span><span class="ot">@aihw2024</span><span class="co">]</span>. The CBD ratio has remained relatively stable, likely reflecting its persistent role as an entertainment and nightlife precinct. Carlton shows a consistently low and declining ratio throughout the period, reflecting its long-established status as a café-centric suburb.</span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a><span class="fu">## Q3: How do income levels and age distributions relate to the pub-to-café ratio?</span></span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a>Two scatterplots are presented as facets, each placing a demographic variable directly on the x-axis against the pub-to-café ratio on the y-axis. This follows the principle that position on a common scale is the most effective encoding for communicating ordered quantitative relationships, more so than colour or size, which were used in earlier spatial designs. Combining the two panels also allows direct visual comparison of how strongly each demographic variable relates to the ratio. Points are sized by total venue count so that small areas do not carry the same visual weight as the CBD; area names are labelled directly on each point.</span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-demo-facet, fig.cap="Faceted scatterplot showing the relationship between the pub-to-café ratio (2024) and two demographic variables from the ABS 2021 Census: weighted average weekly income (left panel) and the proportion of residents aged 18--34 (right panel). Each point is a CLUE small area, sized by total venue count. A trend line with 95% confidence interval is fitted to each panel.", fig.height=4.5, fig.width=8}</span></span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape venue_census into long form for faceting</span></span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a>facet_data <span class="ot">&lt;-</span> venue_census <span class="sc">%&gt;%</span></span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ratio_bar_cafe), <span class="sc">!</span><span class="fu">is.na</span>(weighted_income), <span class="sc">!</span><span class="fu">is.na</span>(pct_18_34)) <span class="sc">%&gt;%</span></span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_label =</span> <span class="fu">dollar</span>(<span class="fu">round</span>(weighted_income, <span class="dv">0</span>)),</span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_label    =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(pct_18_34, <span class="dv">1</span>), <span class="st">"%"</span>)</span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(area, ratio_bar_cafe, total_venues, weighted_income, pct_18_34) <span class="sc">%&gt;%</span></span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols      =</span> <span class="fu">c</span>(weighted_income, pct_18_34),</span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to  =</span> <span class="st">"demographic"</span>,</span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"value"</span></span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a>    <span class="at">demographic =</span> <span class="fu">recode</span>(demographic,</span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a>      <span class="at">weighted_income =</span> <span class="st">"Avg. weekly income (2021 Census, $)"</span>,</span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a>      <span class="at">pct_18_34       =</span> <span class="st">"Residents aged 18–34 (%)"</span></span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-493"><a href="#cb1-493" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(facet_data,</span>
<span id="cb1-494"><a href="#cb1-494" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> ratio_bar_cafe, <span class="at">size =</span> total_venues, <span class="at">label =</span> area)) <span class="sc">+</span></span>
<span id="cb1-495"><a href="#cb1-495" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>,</span>
<span id="cb1-496"><a href="#cb1-496" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#E65100"</span>, <span class="at">fill =</span> <span class="st">"#FFE0B2"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb1-497"><a href="#cb1-497" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"#1565C0"</span>, <span class="at">alpha =</span> <span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb1-498"><a href="#cb1-498" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">size =</span> <span class="fl">2.6</span>, <span class="at">max.overlaps =</span> <span class="dv">15</span>,</span>
<span id="cb1-499"><a href="#cb1-499" aria-hidden="true" tabindex="-1"></a>                  <span class="at">segment.colour =</span> <span class="st">"grey60"</span>, <span class="at">segment.size =</span> <span class="fl">0.3</span>,</span>
<span id="cb1-500"><a href="#cb1-500" aria-hidden="true" tabindex="-1"></a>                  <span class="at">min.segment.length =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb1-501"><a href="#cb1-501" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> demographic, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb1-502"><a href="#cb1-502" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">9</span>), <span class="at">name =</span> <span class="st">"Total venues"</span>,</span>
<span id="cb1-503"><a href="#cb1-503" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb1-504"><a href="#cb1-504" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb1-505"><a href="#cb1-505" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Pub-to-café ratio (2024)"</span>,</span>
<span id="cb1-506"><a href="#cb1-506" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Demographic correlates of pub-to-café ratio by CLUE area"</span>) <span class="sc">+</span></span>
<span id="cb1-507"><a href="#cb1-507" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb1-508"><a href="#cb1-508" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1-509"><a href="#cb1-509" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position  =</span> <span class="st">"right"</span>,</span>
<span id="cb1-510"><a href="#cb1-510" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text       =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb1-511"><a href="#cb1-511" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb1-512"><a href="#cb1-512" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-513"><a href="#cb1-513" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-514"><a href="#cb1-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-515"><a href="#cb1-515" aria-hidden="true" tabindex="-1"></a>@fig-demo-facet shows a modest positive relationship in its left panel between average weekly income and the pub-to-café ratio. The CBD and Southbank (the two largest points) sit at the high end of both axes, suggesting that affluent, mixed-use entertainment precincts sustain a greater pub presence. Carlton is a notable outlier: despite having a relatively high average income (driven by proximity to the university and gentrification), it has one of the lowest pub-to-café ratios, reflecting its deep-rooted café culture. The right panel tells a different story: there is no meaningful positive relationship between the share of young adults (18–34) and the pub-to-café ratio. If anything, the trend is slightly negative. Carlton and Parkville, both areas with large student and young adult populations, cluster in the lower-right, combining high youth share with low pub prevalence. This is consistent with national evidence of declining alcohol consumption among younger Australians <span class="co">[</span><span class="ot">@aihw2024</span><span class="co">]</span>, and suggests that the presence of young residents does not translate into greater pub dominance at the area level. Taken together, the two panels indicate that precinct character and income level are more relevant to pub prevalence than the age structure of the resident population.</span>
<span id="cb1-516"><a href="#cb1-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-517"><a href="#cb1-517" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb1-518"><a href="#cb1-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-519"><a href="#cb1-519" aria-hidden="true" tabindex="-1"></a>This analysis explored the distribution and relative balance of cafés and pubs across the City of Melbourne's CLUE small areas using venue data from 2002–2024 and ABS Census data from 2016 and 2021.</span>
<span id="cb1-520"><a href="#cb1-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-521"><a href="#cb1-521" aria-hidden="true" tabindex="-1"></a>In response to **Question 1**, cafés and pubs are concentrated heavily in the Melbourne CBD, with Carlton, Docklands, and Southbank as secondary clusters. Cafés consistently outnumber pubs in every CLUE area, reflecting Melbourne's strong coffee culture.</span>
<span id="cb1-522"><a href="#cb1-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-523"><a href="#cb1-523" aria-hidden="true" tabindex="-1"></a>Regarding **Question 2**, the pub-to-café ratio has declined across most areas over the 22-year study period, most dramatically in Docklands and Southbank. This temporal trend is consistent with a city-wide cultural shift towards café culture, aligning with national evidence of declining alcohol consumption in younger generations <span class="co">[</span><span class="ot">@aihw2024</span><span class="co">]</span>.</span>
<span id="cb1-524"><a href="#cb1-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-525"><a href="#cb1-525" aria-hidden="true" tabindex="-1"></a>For **Question 3**, the faceted scatterplot revealed that pub dominance is more strongly associated with higher-income entertainment precincts than with areas that have large young adult populations. Carlton and Parkville, both youth-heavy, have among the lowest pub-to-café ratios, while the CBD and Southbank combine high income with high pub presence. This challenges the intuitive assumption that younger residents drive pub culture, and instead points to the role of precinct character and income level.</span>
<span id="cb1-526"><a href="#cb1-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-527"><a href="#cb1-527" aria-hidden="true" tabindex="-1"></a>The analysis was limited by the coarse spatial granularity of the CLUE area system (13 zones) and by the approximate SA2-to-CLUE crosswalk required to link census data. Future work could incorporate finer spatial units and foot traffic data to better account for non-resident demand.</span>
<span id="cb1-528"><a href="#cb1-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-529"><a href="#cb1-529" aria-hidden="true" tabindex="-1"></a><span class="fu"># Reflection</span></span>
<span id="cb1-530"><a href="#cb1-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-531"><a href="#cb1-531" aria-hidden="true" tabindex="-1"></a>This project reinforced several key lessons about data visualisation and exploratory analysis. First, the choice of visual encoding matters enormously: switching from a raw count bar chart (@fig-venue-counts) to a ratio visualisation revealed a completely different spatial pattern, highlighting how the framing of a question shapes what we see. Second, the faceted scatterplot for Question 3 was chosen over spatial maps because the core question is about the relationship between demographics and the ratio, and position on a common scale encodes that relationship more precisely than colour or size on a map. This reflects the principle that just because data has a geographic component does not mean it should always be mapped.</span>
<span id="cb1-532"><a href="#cb1-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-533"><a href="#cb1-533" aria-hidden="true" tabindex="-1"></a>In hindsight, using proper polygon boundary data (ABS SA2 shapefiles or City of Melbourne CLUE area boundaries) to produce choropleth maps would have made the spatial encoding even more precise and visually compelling. I would also have liked to explore venue density per capita rather than raw counts, which would account for the very different resident populations across areas. Finally, the name-based café filter, while defensible, could be improved with a supervised classification approach trained on a manually labelled sample of venue names.</span>
<span id="cb1-534"><a href="#cb1-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-535"><a href="#cb1-535" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bibliography</span></span>
<span id="cb1-536"><a href="#cb1-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-537"><a href="#cb1-537" aria-hidden="true" tabindex="-1"></a>::: {#refs}</span>
<span id="cb1-538"><a href="#cb1-538" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-539"><a href="#cb1-539" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-540"><a href="#cb1-540" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-541"><a href="#cb1-541" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-542"><a href="#cb1-542" aria-hidden="true" tabindex="-1"></a><span class="fu"># Generative AI Declaration</span></span>
<span id="cb1-543"><a href="#cb1-543" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-544"><a href="#cb1-544" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Link 1</span><span class="co">](https://chatgpt.com/share/69e9badd-85c0-839a-82c0-d119188d199b)</span> helped me write the R code to join ABS data G04 &amp; G17</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Ibtesam Ifaz · Built with <a href="https://quarto.org">Quarto</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>